export const ROUTES = {
  HOME: '/',
  COMPLETE_SIGNUP: '/complete-signup',
  ADMIN_PANEL: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_RESERVATIONS: '/admin/reservations',
  ADMIN_FLIGHTS: '/admin/flights',
  FLIGHT: '/flights/:id',
  RESERVATIONS: '/reservations',
  RESERVATION_DETAILS: '/reservations/:id',
  PAYMENT: '/payment',
  BOARDING: '/boarding/:id',
  PASSENGERS: '/passengers/:id',
  PROFILE: '/profile',
  REPORTS: '/admin/reports',
} as const;